version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
    # ignore:
    #   - dependency-name: "junit:junit"
    #     versions: ["4.x"]
