name: Export Open GHAS Alerts of ORG
on:
  workflow_dispatch:  
  schedule:
    - cron: "0 0 * * 1" 

jobs:
  export-org-security-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Export Open Alerts to CSV
        uses: advanced-security/ghas-to-csv@v3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          GITHUB_REPORT_SCOPE: "organization"
          SCOPE_NAME: "CanarysPlayground"
          GITHUB_ALERT_STATUS: "open"  

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: open-ghas-alerts
          path: "./**/*.csv"
          if-no-files-found: warn
