name: Send logs to Datadog

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  log_to_datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Send log to Datadog
        run: |
          curl -X POST "https://http-intake.logs.us5.datadoghq.com/v1/input" \
          -H "Content-Type: application/json" \
          -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
          -d '{
                "message": "GitHub push event",
                "ddsource": "github",
                "service": "ci-pipeline"
              }'
