name: Export Org Code Scanning Alerts

on:
  workflow_dispatch:

jobs:
  export-all-alerts:
    runs-on: ubuntu-latest

    env:
      ORG: CanarysPlayground
      GH_PAT: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Check API auth and fetch repos
        id: fetch-repos
        run: |
          echo "🔐 Testing GitHub API access for org: $ORG"
          response=$(curl -s -H "Authorization: token $GH_PAT" \
                          "https://api.github.com/orgs/$ORG/repos?per_page=100&type=all")

          echo "$response" | jq type > /dev/null 2>&1 || {
            echo "❌ Failed to parse response. Raw output:"
            echo "$response"
            exit 1
          }

          echo "$response" | jq -r '.[].full_name' > repos.txt

          if [ ! -s repos.txt ]; then
            echo "❌ No repositories found or insufficient permissions."
            echo "$response"
            exit 1
          fi

          echo "✅ Repositories fetched:"
          cat repos.txt

      - name: Export code scanning alerts per repo
        run: |
          mkdir -p results
          while read repo; do
            echo "🔍 Fetching alerts for $repo..."
            curl -s -H "Authorization: token $GH_PAT" \
                 -H "Accept: application/vnd.github+json" \
                 "https://api.github.com/repos/$repo/code-scanning/alerts?per_page=100" \
                 -o "results/${repo//\//_}_alerts.json"
          done < repos.txt

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: org-code-scanning-alerts
          path: results/
