name: Export Org Code Scanning Alerts

on:
  workflow_dispatch:

jobs:
  export-all-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Set up variables
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
        run: |
          echo "ORG=my-org-name" >> $GITHUB_ENV
          echo "TOKEN=$GH_TOKEN" >> $GITHUB_ENV

      - name: Fetch all repos in org
        id: fetch-repos
        run: |
          curl -s -H "Authorization: token $TOKEN" \
               "https://api.github.com/orgs/$ORG/repos?per_page=100&type=all" \
               | jq -r '.[].full_name' > repos.txt

      - name: Export code scanning alerts for each repo
        run: |
          mkdir -p results
          while read repo; do
            echo "Fetching alerts for $repo..."
            curl -s -H "Authorization: token $TOKEN" \
                 -H "Accept: application/vnd.github+json" \
                 "https://api.github.com/repos/$repo/code-scanning/alerts?per_page=100" \
                 -o "results/${repo//\//_}_alerts.json"
          done < repos.txt

      - name: Upload all alerts as artifact
        uses: actions/upload-artifact@v4
        with:
          name: org-code-scanning-alerts
          path: results/
