name: Create AWS EC2 Instance

on:
  workflow_dispatch: 
jobs:
   List-EC2-Instances1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: "AKIA6JKEXY2NB5F65KEP"
        aws-secret-access-key: "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"
        aws-region: "ap-south-1"

        
        #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #aws-region: ${{ secrets.AWS_REGION }}

    - name: List EC2 Instances
      run: |
        aws ec2 describe-instances \
          --query 'Reservations[*].Instances[*].[InstanceId,State.Name,PublicIpAddress]' \
          --output table

          
   List-EC2-Instances2:
     runs-on: ubuntu-latest
     environment: instancetest
     needs: List-EC2-Instances1

     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
      
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
        
           aws-access-key-id: ${{ secrets.ACCESS_KEY_ }}
           aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.REGION }}

       - name: List EC2 Instances
         run: |
           aws ec2 describe-instances \
             --query 'Reservations[*].Instances[*].[InstanceId,State.Name,PublicIpAddress]' \
             --output table
