name: Export GHAS Data of ORG
on:
  push:
jobs:
  export-org-security-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: CSV export
        uses: advanced-security/ghas-to-csv@v3
        env:
          GITHUB_PAT: ${{ secrets.GH_TOKEN }}
          GITHUB_REPORT_SCOPE: "organization"
          SCOPE_NAME: "CanarysPlayground"

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: org-ghas-data
          path: "*.csv"
          if-no-files-found: warn
