name: alerts-to-owasp10
on:
  push:
    branches:
      - main  

jobs:
  export-org-security-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: OWASP Top 10 Alerts
        uses: KittyChiu/alerts-to-owasp10@v0.1.2
        env:
          ORGANISATION: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPORT_SCOPE: "organization"
          SCOPE_NAME: "CanarysPlayground"
      
      - name: Process and Filter Alerts
        run: |
          pip install pandas
          python << EOF
          import pandas as pd
          import glob
          import os

          # Load all CSV files
          csv_files = glob.glob("*.csv")
          
          for file in csv_files:
              try:
                  # Read the CSV file
                  df = pd.read_csv(file)
                  
                  # Sort by severity (descending) and date (descending)
                  # Assumes columns 'Severity' and 'Date' exist
                  df_sorted = df.sort_values(by=['Severity', 'Date'], ascending=[False, False])
                  
                  # Group by repository and take top 10 alerts
                  df_filtered = df_sorted.groupby('Repo_Name').apply(lambda x: x.head(10)).reset_index(drop=True)
                  
                  # Save the filtered results
                  df_filtered.to_csv(file, index=False)
                  
                  print(f"Processed {file}: Filtered to top 10 alerts")
              except Exception as e:
                  print(f"Error processing {file}: {e}")
          EOF
      
      - name: Upload Filtered CSV
        uses: actions/upload-artifact@v4
        with:
          name: top-10-owasp-alerts
          path: "*.csv"
          if-no-files-found: warn
