name: alerts-to-owasp10

on:
  push:
  workflow_dispatch:

jobs:
  export-repo-security-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: OWASP Top 10
        uses: KittyChiu/alerts-to-owasp10@v0.1.2
        env:
          ORGANISATION: CanarysPlayground
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPORT_SCOPE: "repository"
          SCOPE_NAME: "CanarysPlayground/Instance"
          ACTIONS_STEP_DEBUG: true

      - name: Filter Top 10 Alerts for Instance Repo
        run: |
          pip install pandas
          python - <<EOF
          import pandas as pd
          import glob

          severity_map = {
              'A01:2021': 'High',
              'A08:2021': 'Medium'
          }

          csv_files = glob.glob("*.csv")
          for file in csv_files:
              df = pd.read_csv(file)
              print(f"Processing {file}:")
              print(df.columns)

              df = df.rename(columns={'repo_name': 'Repo_Name'})

              # Filter only for 'Instance' repo
              df = df[df['Repo_Name'] == 'Instance']

              df['Severity'] = df['risk'].str.split(' ').str[0].map(severity_map)
              severity_order = {'High': 3, 'Medium': 2, 'Low': 1}
              df['Severity_Score'] = df['Severity'].map(severity_order).fillna(0)

              df_sorted = df.sort_values(by=['Severity_Score', 'alert_no'], ascending=[False, False])
              df_filtered = df_sorted.groupby('Repo_Name').head(10)
              df_filtered = df_filtered.drop(columns=['Severity_Score'])
              df_filtered.to_csv(file, index=False)
          EOF

      - name: Upload Filtered CSV
        uses: actions/upload-artifact@v4
        with:
          name: instance-ghas-data
          path: "*.csv"
          if-no-files-found: warn
