name: alerts-to-owasp10
on:
  push:
jobs:
  export-org-security-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: OWASP Top 10
        uses: KittyChiu/alerts-to-owasp10@v0.1.2
        env:
            ORGANISATION: ${{ github.repository_owner }}
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            GITHUB_REPORT_SCOPE: "organization"
            SCOPE_NAME: "CanarysPlayground"

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: org-ghas-data
          path: "*.csv"
          if-no-files-found: warn
