name: alerts-to-owasp10
on:
  push:
jobs:
  export-org-security-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: OWASP Top 10
        uses: KittyChiu/alerts-to-owasp10@v0.1.2
        env:
          ORGANISATION: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPORT_SCOPE: "organization"
          SCOPE_NAME: "CanarysPlayground"

      - name: Filter Top 10 Alerts per Repository
        run: |
          pip install pandas
          python - <<EOF
          import pandas as pd
          import glob
      
          # Load all CSV files matching the pattern
          csv_files = glob.glob("*.csv")
          for file in csv_files:
              df = pd.read_csv(file)
              print(f"Processing {file}:")
              print(df.columns)  # Print columns to verify their names
              # Adjust column names as per your CSV structure
              df_sorted = df.sort_values(by=['Severity', 'Date'], ascending=[False, False])
              df_filtered = df_sorted.groupby('Repo_Name').head(10)
              df_filtered.to_csv(file, index=False)
          EOF


      - name: Upload Filtered CSV
        uses: actions/upload-artifact@v4
        with:
          name: org-ghas-data
          path: "*.csv"
          if-no-files-found: warn
