name: Security Policy Enforcement

on:
  push: 
  
  # pull_request:
  #   branches:
  #     - main

jobs:
  policy-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Advanced Security Policy as Code
        uses: advanced-security/policy-as-code@v2.9.1
        with:
          policy-path: '../../security-policy.yml'
          github-token: ${{ secrets.GITHUB_TOKEN }}
